[Input.stick]
sideways = 0
forward = 1
twist = 2
slider = 3

[Input.controller]
left = { sideways = 0, forward = 1, trigger = 2 }
right = { sideways = 3, forward = 4, trigger = 5 }

[Operator.drive]
controller_index = 0
move_axis = "Input.controller.left.forward"
rotate_axis = "Input.controller.right.sideways"
damping_axis = "Input.controller.right.trigger"

[Operator.lift]
stick_index = 1
stick_deadzone = 0.2
claw_axis = "Operator.stick.forward"
cone = { consume = 3, barfing = 5 }
cube = { consume = 4, barfing = 6 }

# 4'10"

# Robot table contains all robot config
[Robot.wheels]
inch_to_encoder = 0.5972222222222222222 #43 ticks per 72 inch
ticks_per_degree = 0.15555555555555555
#ticks_per_rotation = 1024
#wheel_diameter_inch = 6
#ticks_per_inch = 54.3248872420336079 #ticks per rotation over perimeter (diameter pi)

[Robot.distance]
# divide voltage by 9.77mV to get cm
# https://www.maxbotix.com/firstrobotics
voltage_to_inch = 40.29691
port = 0

[Robot.gyro]
multiplier = 1.0
turn_epsilon = 20.0

[Robot.pid]
drive_pid = { p = 1.0, i = 0.5, d = 0.0 }
turn_pid = { p = 1.0, i = 0.0, d = 0.0 }

[Robot.limits]
max_turn_rate = 10.0
max_turn_accel = 30.0

[Robot.motors]
left_front = 3
left_back = 4
right_front = 1
right_back = 2
rotation_arm = 6
claw_motor = 7

[Robot.arm]
arm_limit = { lower = 0.0, upper = 120.0 }


[Auto]
distance_inch = 200.0
drive_speed = 0.3
